export interface TeamMember {
  name: string;
  role: string;
  id: string;
  cyberRole: string;
  avatar: string;
  bio: string;
}

export interface TrackerState {
  sunAngle: number; // in degrees (0 to 180)
  panelAngle: number; // in degrees (0 to 180)
  ldrLeft: number; // simulated solar intensity (0 to 1023)
  ldrRight: number; // simulated solar intensity (0 to 1023)
  isAuto: boolean; // boolean tracker status
  voltage: number; // simulated current voltage output (e.g., peak 5V or 12V tracker)
  power: number; // simulated current power generated (W)
  currentDayGeneration: number; // Wh total accumulated today
  efficiency: number; // relative efficiency compared to fixed panel (%)
  isTrackingActive: boolean; // tracking motor spinning or fine aligned
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
}

export interface TelemetryData {
  time: string;
  capsPower: number; // Power generated by CAPS Tracker (W)
  fixedPower: number; // Power generated by a fixed panel (W)
  diff: number; // Gained performance
}
